DECLARE @Unit_Units INT;
DECLARE @Unit_UnitsPerSec INT;
DECLARE @Unit_UnitsPerMin INT;
DECLARE @Unit_Hours INT;
SELECT @Unit_Units = EUKey FROM dbo.EngineeringUnit WHERE Unit = N'units';
SELECT @Unit_UnitsPerSec = EUKey FROM dbo.EngineeringUnit WHERE Unit = N'units/s';
SELECT @Unit_UnitsPerMin = EUKey FROM dbo.EngineeringUnit WHERE Unit = N'units/min';
SELECT @Unit_Hours = EUKey FROM dbo.EngineeringUnit WHERE Unit = N'Hour';

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysCritErrCnt',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total Critical errors since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysCritErrCnt',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 1000,
    @MinRaw = 0,
    @MaxRaw = 1000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysFatalErrCnt',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total Fatal errors since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysFatalErrCnt',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 1000,
    @MinRaw = 0,
    @MaxRaw = 1000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysErrErrCnt',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = 'Total non-fatal errors since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysErrErrCnt',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 10000,
    @MinRaw = 0,
    @MaxRaw = 10000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysWarnErrCnt',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total warnings since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysWarnErrCnt',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 10000,
    @MinRaw = 0,
    @MaxRaw = 10000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusRxTotalItems',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total items received from SysDrv since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusRxTotalItems',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 2000000000,
    @MinRaw = 0,
    @MaxRaw = 2000000000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusRxItemsPerSec',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Items per second received from Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusRxItemsPerSec',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 10000,
    @MinRaw = 0,
    @MaxRaw = 10000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysSpaceMain',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Space left on Circular Data Path',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @TimeDeadband = 300000,
    @ItemName = N'SysSpaceMain',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 100000,
    @MinRaw = 0,
    @MaxRaw = 100000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysSpaceAlt',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Space left on Alternative Data Path',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @TimeDeadband = 300000,
    @ItemName = N'SysSpaceAlt',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 100000,
    @MinRaw = 0,
    @MaxRaw = 100000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysSpaceBuffer',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Space left on Buffer Data Path',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @TimeDeadband = 300000,
    @ItemName = N'SysSpaceBuffer',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 100000,
    @MinRaw = 0,
    @MaxRaw = 100000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysSpacePerm',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Space left on Permanent Data Path',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @TimeDeadband = 300000,
    @ItemName = N'SysSpacePerm',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 100000,
    @MinRaw = 0,
    @MaxRaw = 100000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysMinutesRun',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Minutes since the last startup',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 60000,
    @ItemName = N'SysMinutesRun',
    @EUKey = @MinUnit,
    @MinEU = 0,
    @MaxEU = 500000,
    @MinRaw = 0,
    @MaxRaw = 500000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysTimeSec',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Time : Seconds',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 1000,
    @ItemName = N'SysTimeSec',
    @EUKey = @SecUnit,
    @MinEU = 0,
    @MaxEU = 59,
    @MinRaw = 0,
    @MaxRaw = 59,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0,
    @RolloverValue = 60;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysTimeMin',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Time : Minutes',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 60000,
    @ItemName = N'SysTimeMin',
    @EUKey = @MinUnit,
    @MinEU = 0,
    @MaxEU = 59,
    @MinRaw = 0,
    @MaxRaw = 59,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0,
    @RolloverValue = 60;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysTimeHour',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Time : Hours',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @ItemName = N'SysTimeHour',
    @EUKey = @HourUnit,
    @MinEU = 0,
    @MaxEU = 23,
    @MinRaw = 0,
    @MaxRaw = 23,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0,
    @RolloverValue = 24;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysDateDay',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Date : Day',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @ItemName = N'SysDateDay',
    @EUKey = @DayUnit,
    @MinEU = 1,
    @MaxEU = 31,
    @MinRaw = 1,
    @MaxRaw = 31,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysDateMonth',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Date : Month',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @ItemName = N'SysDateMonth',
    @EUKey = @MonthUnit,
    @MinEU = 1,
    @MaxEU = 12,
    @MinRaw = 1,
    @MaxRaw = 12,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysDateYear',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Date : Year',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 300000,
    @ItemName = N'SysDateYear',
    @EUKey = @YearUnit,
    @MinEU = 0,
    @MaxEU = 2050,
    @MinRaw = 0,
    @MaxRaw = 2050,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysConfigStatus',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Configuration Status (Re-init tracking)',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 10000,
    @ItemName = N'SysConfigStatus',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 200,
    @MinRaw = 0,
    @MaxRaw = 200,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfCPUTotal',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU total processor load',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfCPUTotal',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfCPUMax',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Maximum %CPU load across processors',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfCPUMax',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for Historian Config Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for Historian Event System',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for Historian Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for Historian DataImport',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for InSQLIOS',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for MS-SQL Server',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalCPU',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'%CPU load for Retrieval Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalCPU',
    @EUKey = @PercentUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the Historian Config Service and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Historian Config Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the Historian Config Service and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the Historian Config Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the Historian Event System and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Historian Event System',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the Historian Event System and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the Historian Event System',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the Historian Classic Data Redirector and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Historian Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the Historian Classic Data Redirector and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the Historian Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the Historian DataImport and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Historian DataImport',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the Historian DataImport and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the Historian Classic Manual Storage',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the HistorianIOS and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Historian IOS',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the HistorianIOS and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the HistorianIOS',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the Historian System Driver and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the Historian System Driver and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the MSSQL Server and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the MS-SQL Server',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the MSSQL Server and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the MSSQL Server',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalPrivateBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes exclusively used by the Historian Retrieval Service and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalPrivateBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalPrivateMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes bytes exclusively used by the Retrieval Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalPrivateMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalVirtualBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of bytes of the virtual address space used by the Historian Retrieval Service and stored as a remainder of division by 4GB',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalVirtualBytes',
    @EUKey = @BytesUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalVirtualMBytes',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Current number of megabytes of the virtual address space used by the Historian Retrieval Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalVirtualMBytes',
    @EUKey = @SpaceUnit,
    @MinEU = 0,
    @MaxEU = 600000000,
    @MinRaw = 0,
    @MaxRaw = 600000000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for Historian Config Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for Historian Event System',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for Historian Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for Historian Classic Manual Storage',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for InSQLIOS',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for MS-SQL Server',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalThreadCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Thread count for Retrieval Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalThreadCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 128,
    @MinRaw = 0,
    @MaxRaw = 128,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for Historian Config Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for Historian Event System',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for Historian Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for Historian Classic Manual Storage',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for InSQLIOS',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for MS-SQL Server',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalHandleCount',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Handle count for Retrieval Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalHandleCount',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 20000,
    @MinRaw = 0,
    @MaxRaw = 20000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 32,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfConfigPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for Historian Config Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfConfigPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfEventSysPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for Historian Event System',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfEventSysPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfClassicDataRedirectorPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for Historian Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfClassicDataRedirectorPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfDataImportPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for Historian DataImport',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfDataImportPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfInSQLIOSPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for InSQLIOS',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfInSQLIOSPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSysDrvPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for Historian System Driver',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSysDrvPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfSQLServerPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for MS-SQL Server',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfSQLServerPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysPerfRetrievalPageFaults',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Page faults per second for Retrieval Service',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 5000,
    @TimeDeadband = 0,
    @ItemName = N'SysPerfRetrievalPageFaults',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 256,
    @MinRaw = 0,
    @MaxRaw = 256,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysEventNormActionQSize',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Classic event system Normal Action Queue Size',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysEventNormActionQSize',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 1000,
    @MinRaw = 0,
    @MaxRaw = 1000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysEventCritActionQSize',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Classic event system Critical Action Queue Size',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysEventCritActionQSize',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 1000,
    @MinRaw = 0,
    @MaxRaw = 1000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysEventDelayedActionQSize',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Classic event system Delayed Action Queue Size',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysEventDelayedActionQSize',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 1000,
    @MinRaw = 0,
    @MaxRaw = 1000,
    @Scaling = 0,
    @RawType = 3,
    @IntegerSize = 16,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysTagHoursQueried',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total retrieval hours queried during the minute',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @TimeDeadband = 0,
    @ItemName = N'SysTagHoursQueried',
    @EUKey = @Unit_Hours,
    @MinEU = 0,
    @MaxEU = 1000000,
    @MinRaw = 0,
    @MaxRaw = 1000000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusRxTotalDuplicateEvents',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total number of duplicate events received since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusRxTotalDuplicateEvents',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 2000000000,
    @MinRaw = 0,
    @MaxRaw = 2000000000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;       
    
EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusRxTotalEvents',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total number of events received since startup',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 10000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusRxTotalEvents',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 2000000000,
    @MinRaw = 0,
    @MaxRaw = 2000000000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;       

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusRxEventsPerSec',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Events per second received',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 1000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusRxEventsPerSec',
    @EUKey = @Unit_UnitsPerSec,
    @MinEU = 0,
    @MaxEU = 10000,
    @MinRaw = 0,
    @MaxRaw = 10000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusEventCommitPending',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Event commit pending',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 1000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusEventCommitPending',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 100000,
    @MinRaw = 0,
    @MaxRaw = 100000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusAverageEventCommitSize',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Average event commit size',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusAverageEventCommitSize',
    @EUKey = @Unit_Units,
    @MinEU = 0,
    @MaxEU = 100000,
    @MinRaw = 0,
    @MaxRaw = 100000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysStatusAverageEventCommitTime',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Average event commit time in seconds',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysStatusAverageEventCommitTime',
    @EUKey = @SecUnit,
    @MinEU = 0,
    @MaxEU = 100,
    @MinRaw = 0,
    @MaxRaw = 100,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;

EXEC dbo.aaAnalogTagInsert
    @TagName = N'SysEventHoursQueried',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Total event retrieval hours queried during the minute',
    @AcquisitionType = 3,
    @StorageType = 1,
    @StorageRate = 60000,
    @TimeDeadband = 0,
    @ItemName = N'SysEventHoursQueried',
    @EUKey = @Unit_Hours,
    @MinEU = 0,
    @MaxEU = 1000000,
    @MinRaw = 0,
    @MaxRaw = 1000000,
    @Scaling = 0,
    @RawType = 2,
    @IntegerSize = 0,
    @SignedInteger = 0;
GO    

EXEC dbo.aaMessageInsert 'OFF', 'ON';

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysPulse',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Pulse',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysPulse',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysClassicDataRedirector',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Classic Data Redirector',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysClassicDataRedirector',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysEventSystem',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'Classic event system Status',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysEventSystem',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysRetrieval',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Lower Retrieval Status',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysRetrieval',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysInSQLIOS',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Wonderware Historian I/O Server Status',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysInSQLIOS',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysConfiguration',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Configuration Status (1 = Configuration changes pending or in progress)',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysConfiguration',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysDataImport',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System DataImport Service Status',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysDataImport',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysSystemDriver',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Driver Service Status',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysSystemDriver',
    @MessageKey = 1;

EXEC dbo.aaDiscreteTagInsert
    @TagName = N'SysOLEDB',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System OLE-DB Provider Status',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysOLEDB',
    @MessageKey = 1;

EXEC dbo.aaStringTagInsert
    @TagName = N'SysString',
    @TopicKey = 1,
    @IOServerKey = 1,
    @Description = N'System Hourly String',
    @AcquisitionType = 3,
    @StorageType = 2,
    @StorageRate = 0,
    @ItemName = N'SysString',
    @MaxLength = 131,
    @InitialValue = N'',
    @DoubleByte = 1;
GO

EXEC dbo.aaEventTagInsert
    @TagName = N'SysStatusEvent',
    @Description = N'Status Tag snapshot event',
    @ScanRate = 60000,
    @TimeDeadband = 0,
    @Logged = 1,
    @DetectorTypeKey = 4,
    @DetectorString = N'EXEC dbo.aaEventDetection N''SysTimeMin'', ''='', 0, N''Leading'', 0, ''@StartTime'', ''@EndTime''',
    @ActionTypeKey = 3,
    @ActionString = N'EXEC dbo.aaEventSnapshotInsert @EventLogKey, ''@EventTime'', N''@EventTagName''',
    @Status = 0,
    @Priority = 0,
    @Edge = 1;